/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module "vue" {
  export interface GlobalComponents {
    AppHeader: (typeof import("./src/components/AppHeader.vue"))["default"];
    CircleProgress: (typeof import("./src/components/CircleProgress.vue"))["default"];
    ColoredCard: (typeof import("./src/components/ColoredCard.vue"))["default"];
    Dot: (typeof import("./src/components/Dot.vue"))["default"];
    DotSymptom: (typeof import("./src/components/DotSymptom.vue"))["default"];
    Loading: (typeof import("./src/components/Loading.vue"))["default"];
    NAlert: (typeof import("naive-ui"))["NAlert"];
    NButton: (typeof import("naive-ui"))["NButton"];
    NButtonGroup: (typeof import("naive-ui"))["NButtonGroup"];
    NCard: (typeof import("naive-ui"))["NCard"];
    NCascader: (typeof import("naive-ui"))["NCascader"];
    NCheckbox: (typeof import("naive-ui"))["NCheckbox"];
    NCheckboxGroup: (typeof import("naive-ui"))["NCheckboxGroup"];
    NDatePicker: (typeof import("naive-ui"))["NDatePicker"];
    NDialog: (typeof import("naive-ui"))["NDialog"];
    NDialogProvider: (typeof import("naive-ui"))["NDialogProvider"];
    NForm: (typeof import("naive-ui"))["NForm"];
    NFormItem: (typeof import("naive-ui"))["NFormItem"];
    NFormItemGi: (typeof import("naive-ui"))["NFormItemGi"];
    NGi: (typeof import("naive-ui"))["NGi"];
    NGlobalStyle: (typeof import("naive-ui"))["NGlobalStyle"];
    NGrid: (typeof import("naive-ui"))["NGrid"];
    NH2: (typeof import("naive-ui"))["NH2"];
    NIcon: (typeof import("naive-ui"))["NIcon"];
    NInput: (typeof import("naive-ui"))["NInput"];
    NInputNumber: (typeof import("naive-ui"))["NInputNumber"];
    NMessageProvider: (typeof import("naive-ui"))["NMessageProvider"];
    NModal: (typeof import("naive-ui"))["NModal"];
    NNotificationProvider: (typeof import("naive-ui"))["NNotificationProvider"];
    NPopover: (typeof import("naive-ui"))["NPopover"];
    NRadio: (typeof import("naive-ui"))["NRadio"];
    NRadioButton: (typeof import("naive-ui"))["NRadioButton"];
    NRadioGroup: (typeof import("naive-ui"))["NRadioGroup"];
    NSelect: (typeof import("naive-ui"))["NSelect"];
    NSkeleton: (typeof import("naive-ui"))["NSkeleton"];
    NSlider: (typeof import("naive-ui"))["NSlider"];
    NSpace: (typeof import("naive-ui"))["NSpace"];
    NSpin: (typeof import("naive-ui"))["NSpin"];
    NSwitch: (typeof import("naive-ui"))["NSwitch"];
    NTimePicker: (typeof import("naive-ui"))["NTimePicker"];
    NTooltip: (typeof import("naive-ui"))["NTooltip"];
    NTransfer: (typeof import("naive-ui"))["NTransfer"];
    PatientForm: (typeof import("./src/components/PatientForm.vue"))["default"];
    ReportTableHeader: (typeof import("./src/components/ReportTableHeader.vue"))["default"];
    RouterLink: (typeof import("vue-router"))["RouterLink"];
    RouterView: (typeof import("vue-router"))["RouterView"];
  }
}
