symptom_descriptions = {
    # --- Determined by conversation log → LLM ---
    "syncope": {
        "description": "Fainting or Syncope",
        "display_name": "Syncope",
        "max_scale": 4,
        "color": "#eb4c44",
        "likert": False,
        "source": "conversation",
    },
    "palpitation": {
        "description": "Heart Palpitations",
        "display_name": "Palpitation",
        "max_scale": 3,
        "color": "#f9d965",
        "likert": False,
        "source": "conversation",
    },
    "short_of_breath": {
        "description": "Shortness of Breath (Dyspnea)",
        "display_name": "Breath",
        "max_scale": 4,
        "color": "#eb4c44",
        "likert": False,
        "source": "conversation",
    },
    "chest_discomfort": {
        "description": "Chest Discomfort or Pain",
        "display_name": "Chest",
        "max_scale": 4,
        "color": "#eb4c44",
        "likert": False,
        "source": "conversation",
    },
    "swelling": {
        "description": "Swelling (Edema)",
        "display_name": "Swelling",
        "max_scale": 3,
        "color": "#f9d965",
        "likert": False,
        "source": "conversation",
    },
    # --- Determined by wearable data → LLM (processed separately) ---
    "heart_rate": {
        "description": "Heart Rate",
        "display_name": "Heart Rate",
        "max_scale": 4,
        "color": "#4bbfd1",
        "likert": False,
        "source": "wearable",
    },
    "respiration": {
        "description": "Respiration Rate",
        "display_name": "Respiration",
        "max_scale": 4,
        "color": "#ffb700",
        "likert": False,
        "source": "wearable",
    },
}