symptom_descriptions = {
    "breathing": {
        "description": "Difficulty Breathing",
        "display_name": "Breathing",
        "max_scale": 4,
        "color": "#eb4c44",
        "likert": True,
    },
    "fever": {
        "description": "Fever",
        "display_name": "Fever",
        "max_scale": 4,
        "color": "#eb4c44",
        "likert": False,
    },
    "stools": {
        "description": "Black, Tar-like Stools",
        "display_name": "Stools",
        "max_scale": 4,
        "color": "#eb4c44",
        "likert": False,
    },
    "pain": {
        "description": "Pain Increase or Unbearable",
        "display_name": "Pain",
        "max_scale": 4,
        "color": "#eb4c44",
        "likert": True,
    },
    "drainage": {
        "description": "Wound Drainage Problems",
        "display_name": "Drainage",
        "max_scale": 3,
        "color": "#f9d965",
        "likert": False,
    },
    "activity": {
        "description": "Decrease in Daily Activities",
        "display_name": "Activity",
        "max_scale": 2,
        "color": "#6283ac",
        "likert": False,
    },
    "conscious": {
        "description": "Decrease in Level of Consciousness",
        "display_name": "Conscious",
        "max_scale": 4,
        "color": "#eb4c44",
        "likert": True,
    },
    "constipation": {
        "description": "Persistent Constipation, Nausea, or Vomiting",
        "display_name": "Vomit",
        "max_scale": 3,
        "color": "#f9d965",
        "likert": True,
    },
    "diarrhea": {
        "description": "Persistent Diarrhea",
        "display_name": "Diarrhea",
        "max_scale": 3,
        "color": "#f9d965",
        "likert": False,
    },
    "eating": {
        "description": "Inability to Tolerate Food or Drink",
        "display_name": "Eating",
        "max_scale": 3,
        "color": "#f9d965",
        "likert": True,
    },
    "swelling": {
        "description": "Pain or swelling in legs",
        "display_name": "Swelling",
        "max_scale": 4,
        "color": "#eb4c44",
        "likert": False,
    },
    "mood": {
        "description": "Feeling Down or Depressed",
        "display_name": "Mood",
        "max_scale": 2,
        "color": "#6283ac",
        "likert": False,
    },
    "misc": {
        "description": "Other Symptoms",
        "display_name": "Misc",
        "max_scale": 3,
        "color": "#ff33db",
        "likert": False,
    },
}
