"""empty message

Revision ID: 176e9d639d63
Revises: f3ec2b3c18cc
Create Date: 2024-11-07 22:12:12.469521

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "176e9d639d63"
down_revision = "f3ec2b3c18cc"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("report", schema=None) as batch_op:
        batch_op.add_column(sa.Column("physical_state", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("physical_logs", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("stress_state", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("stress_logs", sa.String(), nullable=True))
        batch_op.drop_column("pain_state")
        batch_op.drop_column("activity_logs")
        batch_op.drop_column("pain_scale")
        batch_op.drop_column("activity_state")
        batch_op.drop_column("eating_state")
        batch_op.drop_column("cognition_logs")
        batch_op.drop_column("pain_logs")
        batch_op.drop_column("eating_logs")
        batch_op.drop_column("cognition_state")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table("report", schema=None) as batch_op:
        batch_op.add_column(sa.Column("cognition_state", sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column("eating_logs", sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column("pain_logs", sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column("cognition_logs", sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column("eating_state", sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column("activity_state", sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column("pain_scale", sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column("activity_logs", sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column("pain_state", sa.INTEGER(), nullable=True))
        batch_op.drop_column("stress_logs")
        batch_op.drop_column("stress_state")
        batch_op.drop_column("physical_logs")
        batch_op.drop_column("physical_state")

    # ### end Alembic commands ###
