"""empty message

Revision ID: 17bf44e8dff9
Revises: 176e9d639d63
Create Date: 2025-03-19 20:53:27.391342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17bf44e8dff9'
down_revision = '176e9d639d63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('garmin_id', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.drop_column('garmin_id')

    # ### end Alembic commands ###
