"""empty message

Revision ID: 2130be66323f
Revises: 7afcd405152b
Create Date: 2024-09-24 22:49:53.104962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2130be66323f'
down_revision = '7afcd405152b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.drop_column('breathing_logs')
        batch_op.drop_column('stools_logs')
        batch_op.drop_column('breathing_state')
        batch_op.drop_column('breathing_scale')
        batch_op.drop_column('pain_scale')
        batch_op.drop_column('swelling_state')
        batch_op.drop_column('pain_logs')
        batch_op.drop_column('drainage_logs')
        batch_op.drop_column('pain_state')
        batch_op.drop_column('swelling_logs')
        batch_op.drop_column('stools_state')
        batch_op.drop_column('drainage_state')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('drainage_state', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('stools_state', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('swelling_logs', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('pain_state', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('drainage_logs', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('pain_logs', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('swelling_state', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('pain_scale', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('breathing_scale', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('breathing_state', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('stools_logs', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('breathing_logs', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
