"""empty message

Revision ID: 374c1d567ec1
Revises: 73366719744c
Create Date: 2024-04-22 16:27:34.482516

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "374c1d567ec1"
down_revision = "73366719744c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("report", schema=None) as batch_op:
        batch_op.add_column(sa.Column("misc_state", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("misc_logs", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("breathing_scale", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("pain_scale", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("conscious_scale", sa.Integer(), nullable=True))
        batch_op.add_column(
            sa.Column("constipation_scale", sa.Integer(), nullable=True)
        )
        batch_op.add_column(sa.Column("eating_scale", sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("report", schema=None) as batch_op:
        batch_op.drop_column("eating_scale")
        batch_op.drop_column("constipation_scale")
        batch_op.drop_column("conscious_scale")
        batch_op.drop_column("pain_scale")
        batch_op.drop_column("breathing_scale")
        batch_op.drop_column("misc_logs")
        batch_op.drop_column("misc_state")

    # ### end Alembic commands ###
