"""empty message

Revision ID: 3b5267430f69
Revises: 17bf44e8dff9
Create Date: 2026-02-01 08:07:22.885207

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.engine import reflection 

# revision identifiers, used by Alembic.
revision = '3b5267430f69'
down_revision = '17bf44e8dff9'
branch_labels = None
depends_on = None

def upgrade():
    # Helper to inspect current database state
    bind = op.get_bind()
    inspector = reflection.Inspector.from_engine(bind)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alexa_id_note',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alexa_user_id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alexa_user_id')
    )
    op.create_table('hospitalization',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('event', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('risk',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('important_of_chest', sa.Float(), nullable=True),
    sa.Column('important_of_heart', sa.Float(), nullable=True),
    sa.Column('important_of_respiration', sa.Float(), nullable=True),
    sa.Column('important_of_hrv', sa.Float(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('summary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('heart_rate_min', sa.Float(), nullable=True),
    sa.Column('heart_rate_max', sa.Float(), nullable=True),
    sa.Column('heart_rate_average', sa.Float(), nullable=True),
    sa.Column('spo2_min', sa.Float(), nullable=True),
    sa.Column('spo2_max', sa.Float(), nullable=True),
    sa.Column('spo2_average', sa.Float(), nullable=True),
    sa.Column('respiration_min', sa.Float(), nullable=True),
    sa.Column('respiration_max', sa.Float(), nullable=True),
    sa.Column('respiration_average', sa.Float(), nullable=True),
    sa.Column('hrv_min', sa.Float(), nullable=True),
    sa.Column('hrv_max', sa.Float(), nullable=True),
    sa.Column('hrv_average', sa.Float(), nullable=True),
    sa.Column('short_of_breath', sa.Boolean(), nullable=True),
    sa.Column('chest_discomfort', sa.Boolean(), nullable=True),
    sa.Column('fatigue', sa.Boolean(), nullable=True),
    sa.Column('palpitation', sa.Boolean(), nullable=True),
    sa.Column('swelling', sa.Boolean(), nullable=True),
    sa.Column('syncope', sa.Boolean(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    with op.batch_alter_table('conversation_log', schema=None) as batch_op:
        # Add new columns
        batch_op.add_column(sa.Column('symptoms_chest', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('symptoms_other', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('date', sa.DateTime(), nullable=False))

        # Alter existing columns
        batch_op.alter_column('patient_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('content',
               existing_type=sa.TEXT(),
               nullable=False)

        # --- FIX: Drop foreign key to 'report' table more robustly ---
        # Get existing foreign keys for 'conversation_log'
        foreign_keys = inspector.get_foreign_keys('conversation_log')
        for fk in foreign_keys:
            # Check if this FK points from 'report_id' column to 'report' table
            if 'report_id' in fk['constrained_columns'] and fk['referred_table'] == 'report':
                if fk.get('name'):
                    batch_op.drop_constraint(fk['name'], type_='foreignkey')
                break # Assuming only one such foreign key

        # --- FIX: Conditionally drop 'report_id' and 'created_at' columns ---
        columns = [c['name'] for c in inspector.get_columns('conversation_log')]
        if 'report_id' in columns:
            batch_op.drop_column('report_id')
        if 'created_at' in columns:
            batch_op.drop_column('created_at')

    with op.batch_alter_table('patient', schema=None) as batch_op:
        # Add new columns
        batch_op.add_column(sa.Column('name', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('cancer_type', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('cancer_stage', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('treatment_type', sa.String(length=100), nullable=True))

        # Create unique constraints (using try-except for robustness if they might already exist)
        try:
            batch_op.create_unique_constraint('uq_patient_alexa_user_id', ['alexa_user_id'])
        except Exception:
            pass # Constraint might already exist
        try:
            batch_op.create_unique_constraint('uq_patient_garmin_id', ['garmin_id'])
        except Exception:
            pass
        try:
            batch_op.create_unique_constraint('uq_patient_participant_id', ['participant_id'])
        except Exception:
            pass

        # Conditionally drop old columns
        columns = [c['name'] for c in inspector.get_columns('patient')]
        if 'reviewed' in columns:
            batch_op.drop_column('reviewed')
        if 'state' in columns:
            batch_op.drop_column('state')
        if 'medication' in columns:
            batch_op.drop_column('medication')
        if 'medical_history' in columns:
            batch_op.drop_column('medical_history')

    with op.batch_alter_table('report_note', schema=None) as batch_op:
        # Add new column
        batch_op.add_column(sa.Column('patient_id', sa.Integer(), nullable=False))

        # Alter existing columns
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('content',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)

        # --- FIX: Drop foreign key to 'report' table more robustly ---
        foreign_keys = inspector.get_foreign_keys('report_note')
        for fk in foreign_keys:
            if 'report_id' in fk['constrained_columns'] and fk['referred_table'] == 'report':
                if fk.get('name'):
                    batch_op.drop_constraint(fk['name'], type_='foreignkey')
                break # Assuming only one such foreign key

        # --- FIX: Create foreign key to 'patient' more robustly ---
        # Check if a foreign key from patient_id to patient.id already exists
        patient_fk_exists = False
        for fk in foreign_keys:
            if 'patient_id' in fk['constrained_columns'] and fk['referred_table'] == 'patient':
                patient_fk_exists = True
                break
        if not patient_fk_exists:
            batch_op.create_foreign_key(
                'fk_report_note_patient_id',
                'patient',
                ['patient_id'],
                ['id'],
            )

        # --- FIX: Conditionally drop 'report_id' column ---
        columns = [c['name'] for c in inspector.get_columns('report_note')]
        if 'report_id' in columns:
            batch_op.drop_column('report_id')

    # Conditionally drop 'report_summary' and 'report' tables
    if 'report_summary' in inspector.get_table_names():
        op.drop_table('report_summary')
    if 'report' in inspector.get_table_names():
        op.drop_table('report')

    with op.batch_alter_table('token', schema=None) as batch_op:
        # Create unique constraint (using try-except for robustness)
        try:
            batch_op.create_unique_constraint('uq_token_token', ['token'])
        except Exception:
            pass

    with op.batch_alter_table('user', schema=None) as batch_op:
        # Create unique constraints (using try-except for robustness)
        try:
            batch_op.create_unique_constraint('uq_user_email', ['email'])
        except Exception:
            pass
        try:
            batch_op.create_unique_constraint('uq_user_username', ['username'])
        except Exception:
            pass

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('token', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('report_note', schema=None) as batch_op:
        batch_op.add_column(sa.Column('report_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'report', ['report_id'], ['id'])
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('content',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('patient_id')

    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('medical_history', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('medication', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('state', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('reviewed', sa.BOOLEAN(), nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('treatment_type')
        batch_op.drop_column('cancer_stage')
        batch_op.drop_column('cancer_type')
        batch_op.drop_column('name')

    with op.batch_alter_table('conversation_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('report_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'report', ['report_id'], ['id'])
        batch_op.alter_column('content',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('patient_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('date')
        batch_op.drop_column('symptoms_other')
        batch_op.drop_column('symptoms_chest')

    op.create_table('report',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('physical_state', sa.INTEGER(), nullable=True),
    sa.Column('physical_logs', sa.VARCHAR(), nullable=True),
    sa.Column('stress_state', sa.INTEGER(), nullable=True),
    sa.Column('stress_logs', sa.VARCHAR(), nullable=True),
    sa.Column('mood_state', sa.INTEGER(), nullable=True),
    sa.Column('mood_logs', sa.VARCHAR(), nullable=True),
    sa.Column('patient_id', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('read', sa.BOOLEAN(), nullable=True),
    sa.Column('misc_state', sa.INTEGER(), nullable=True),
    sa.Column('misc_logs', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('report_summary',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('report_id', sa.INTEGER(), nullable=True),
    sa.Column('category', sa.VARCHAR(length=50), nullable=True),
    sa.Column('content', sa.TEXT(), nullable=True),
    sa.Column('conversation_log_ids', sa.VARCHAR(), nullable=True),
    sa.Column('highlight_keywords', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['report.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('summary')
    op.drop_table('risk')
    op.drop_table('hospitalization')
    op.drop_table('alexa_id_note')
    # ### end Alembic commands ###
