"""empty message

Revision ID: 40d66b3408da
Revises: ea302dd456b9
Create Date: 2024-09-06 19:54:22.947078

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "40d66b3408da"
down_revision = "ea302dd456b9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_patient_table",
        sa.Column("patient_id", sa.Integer(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patient.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_patient_table")
    # ### end Alembic commands ###
