"""init

Revision ID: 5193b57cd38b
Revises:
Create Date: 2024-04-14 01:22:32.572078

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5193b57cd38b"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "patient",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("age", sa.Integer(), nullable=True),
        sa.Column("gender", sa.String(length=10), nullable=True),
        sa.Column("EHR_id", sa.String(length=50), nullable=True),
        sa.Column("alexa_user_id", sa.String(length=50), nullable=True),
        sa.Column("medical_history", sa.Text(), nullable=True),
        sa.Column("medication", sa.Text(), nullable=True),
        sa.Column("participant_id", sa.String(length=20), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=50), nullable=True),
        sa.Column("password", sa.String(length=255), nullable=True),
        sa.Column("email", sa.String(length=100), nullable=True),
        sa.Column("name", sa.String(length=100), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "report",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("patient_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("pain", sa.JSON(), nullable=True),
        sa.Column("breathing", sa.JSON(), nullable=True),
        sa.Column("fever", sa.JSON(), nullable=True),
        sa.Column("stools", sa.JSON(), nullable=True),
        sa.Column("drainage", sa.JSON(), nullable=True),
        sa.Column("activity", sa.JSON(), nullable=True),
        sa.Column("conscious", sa.JSON(), nullable=True),
        sa.Column("constipation", sa.JSON(), nullable=True),
        sa.Column("diarrhea", sa.JSON(), nullable=True),
        sa.Column("eating", sa.JSON(), nullable=True),
        sa.Column("swelling", sa.JSON(), nullable=True),
        sa.Column("mood", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patient.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "conversation_log",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("patient_id", sa.Integer(), nullable=True),
        sa.Column("report_id", sa.Integer(), nullable=True),
        sa.Column("role", sa.String(length=50), nullable=True),
        sa.Column("content", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patient.id"],
        ),
        sa.ForeignKeyConstraint(
            ["report_id"],
            ["report.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "report_note",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("report_id", sa.Integer(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("content", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["report_id"],
            ["report.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "report_summary",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("report_id", sa.Integer(), nullable=True),
        sa.Column("category", sa.String(length=50), nullable=True),
        sa.Column("content", sa.Text(), nullable=True),
        sa.Column("conversation_log_ids", sa.String(), nullable=True),
        sa.Column("highlight_keywords", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["report_id"],
            ["report.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("report_summary")
    op.drop_table("report_note")
    op.drop_table("conversation_log")
    op.drop_table("report")
    op.drop_table("user")
    op.drop_table("patient")
    # ### end Alembic commands ###
