"""empty message

Revision ID: 602be74c86d7
Revises: 374c1d567ec1
Create Date: 2024-08-08 22:05:13.864846

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "602be74c86d7"
down_revision = "374c1d567ec1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "token",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("token", sa.String(length=255), nullable=True),
        sa.Column("userid", sa.Integer(), nullable=False),
        sa.Column("rememberme", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["userid"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("token")
    # ### end Alembic commands ###
