"""empty message

Revision ID: 6f1f9f858851
Revises: 9d9b2e058c52
Create Date: 2024-04-16 22:35:56.562864

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6f1f9f858851"
down_revision = "9d9b2e058c52"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("conversation_log", schema=None) as batch_op:
        batch_op.add_column(sa.Column("chain_of_thoughts", sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("conversation_log", schema=None) as batch_op:
        batch_op.drop_column("chain_of_thoughts")

    # ### end Alembic commands ###
