"""empty message

Revision ID: 703386799acf
Revises: 8c6d0b91a2ef
Create Date: 2026-03-12 10:33:36.331077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '703386799acf'
down_revision = '8c6d0b91a2ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admission_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('admission_date', sa.DateTime(), nullable=False),
    sa.Column('discharge_date', sa.DateTime(), nullable=True),
    sa.Column('diagnosis', sa.Text(), nullable=True),
    sa.Column('symptoms', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('careunit_id', sa.String(length=20), nullable=True),
    sa.Column('careunit_name', sa.String(length=100), nullable=True),
    sa.Column('destination_unit_id', sa.String(length=20), nullable=True),
    sa.Column('destination_unit_name', sa.String(length=100), nullable=True),
    sa.Column('discharge_status', sa.String(length=50), nullable=True),
    sa.Column('admission_type', sa.String(length=30), nullable=True),
    sa.Column('readmission_flag', sa.Boolean(), nullable=True),
    sa.Column('los_minutes', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('admission_history', schema=None) as batch_op:
        batch_op.create_index('ix_admission_history_patient_date', ['patient_id', 'admission_date'], unique=False)

    op.create_table('medication',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('drug_name', sa.String(length=255), nullable=False),
    sa.Column('dosage', sa.String(length=255), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('recorded_by_user_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('route', sa.String(length=50), nullable=True),
    sa.Column('frequency', sa.String(length=50), nullable=True),
    sa.Column('schedule_hours', sa.String(length=100), nullable=True),
    sa.Column('dose_count', sa.Integer(), nullable=True),
    sa.Column('is_current_medication', sa.Boolean(), nullable=True),
    sa.Column('order_source', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.ForeignKeyConstraint(['recorded_by_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('medication', schema=None) as batch_op:
        batch_op.create_index('ix_medication_patient_start', ['patient_id', 'start_date'], unique=False)

    op.create_table('note',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('creator_type', sa.String(length=10), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('io_metric',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('admission_history_id', sa.Integer(), nullable=True),
    sa.Column('metric_date', sa.Date(), nullable=True),
    sa.Column('io_event_count', sa.Integer(), nullable=False),
    sa.Column('io_total_volume_ml', sa.Float(), nullable=False),
    sa.Column('io_total_volume_measurement_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['admission_history_id'], ['admission_history.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('io_metric', schema=None) as batch_op:
        batch_op.create_index('ix_io_metric_patient_date', ['patient_id', 'metric_date'], unique=False)

    op.create_table('medication_execution_metric',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('admission_history_id', sa.Integer(), nullable=True),
    sa.Column('metric_date', sa.Date(), nullable=True),
    sa.Column('ad_event_count', sa.Integer(), nullable=False),
    sa.Column('me_event_count', sa.Integer(), nullable=False),
    sa.Column('so_event_count', sa.Integer(), nullable=False),
    sa.Column('med_admin_execution_event_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['admission_history_id'], ['admission_history.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('medication_execution_metric', schema=None) as batch_op:
        batch_op.create_index('ix_med_exec_patient_date', ['patient_id', 'metric_date'], unique=False)

    op.create_table('preadmission_medication',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('admission_history_id', sa.Integer(), nullable=True),
    sa.Column('drug_name', sa.String(length=255), nullable=False),
    sa.Column('dosage', sa.String(length=255), nullable=True),
    sa.Column('frequency', sa.String(length=100), nullable=True),
    sa.Column('started_before_admission_date', sa.DateTime(), nullable=True),
    sa.Column('active_at_admission', sa.Boolean(), nullable=True),
    sa.Column('source_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['admission_history_id'], ['admission_history.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('preadmission_medication', schema=None) as batch_op:
        batch_op.create_index('ix_preadm_med_admission', ['admission_history_id'], unique=False)
        batch_op.create_index('ix_preadm_med_patient', ['patient_id'], unique=False)

    op.drop_table('report_note')
    op.drop_table('hospitalization')
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('treatment_plan', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('treatment_cycle', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('next_appointment_date', sa.DateTime(), nullable=True))

    with op.batch_alter_table('summary', schema=None) as batch_op:
        batch_op.add_column(sa.Column('read', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('heart_rate_state', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('heart_rate_logs', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('respiration_state', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('respiration_logs', sa.String(), nullable=True))
        batch_op.drop_column('heart_rate_average')
        batch_op.drop_column('spo2_min')
        batch_op.drop_column('hrv_average')
        batch_op.drop_column('respiration_average')
        batch_op.drop_column('heart_rate_max')
        batch_op.drop_column('hrv_min')
        batch_op.drop_column('respiration_min')
        batch_op.drop_column('heart_rate_min')
        batch_op.drop_column('hrv_max')
        batch_op.drop_column('respiration_max')
        batch_op.drop_column('spo2_average')
        batch_op.drop_column('spo2_max')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('summary', schema=None) as batch_op:
        batch_op.add_column(sa.Column('spo2_max', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('spo2_average', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('respiration_max', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('hrv_max', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('heart_rate_min', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('respiration_min', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('hrv_min', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('heart_rate_max', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('respiration_average', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('hrv_average', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('spo2_min', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('heart_rate_average', sa.FLOAT(), nullable=True))
        batch_op.drop_column('respiration_logs')
        batch_op.drop_column('respiration_state')
        batch_op.drop_column('heart_rate_logs')
        batch_op.drop_column('heart_rate_state')
        batch_op.drop_column('read')

    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.drop_column('next_appointment_date')
        batch_op.drop_column('treatment_cycle')
        batch_op.drop_column('treatment_plan')

    op.create_table('hospitalization',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('patient_id', sa.INTEGER(), nullable=False),
    sa.Column('date', sa.DATETIME(), nullable=False),
    sa.Column('event', sa.VARCHAR(length=500), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('report_note',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.Column('patient_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], name='fk_report_note_patient_id'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('preadmission_medication', schema=None) as batch_op:
        batch_op.drop_index('ix_preadm_med_patient')
        batch_op.drop_index('ix_preadm_med_admission')

    op.drop_table('preadmission_medication')
    with op.batch_alter_table('medication_execution_metric', schema=None) as batch_op:
        batch_op.drop_index('ix_med_exec_patient_date')

    op.drop_table('medication_execution_metric')
    with op.batch_alter_table('io_metric', schema=None) as batch_op:
        batch_op.drop_index('ix_io_metric_patient_date')

    op.drop_table('io_metric')
    op.drop_table('note')
    with op.batch_alter_table('medication', schema=None) as batch_op:
        batch_op.drop_index('ix_medication_patient_start')

    op.drop_table('medication')
    with op.batch_alter_table('admission_history', schema=None) as batch_op:
        batch_op.drop_index('ix_admission_history_patient_date')

    op.drop_table('admission_history')
    # ### end Alembic commands ###
