"""empty message

Revision ID: 73366719744c
Revises: 6f1f9f858851
Create Date: 2024-04-18 00:09:42.784533

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "73366719744c"
down_revision = "6f1f9f858851"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("patient", schema=None) as batch_op:
        batch_op.add_column(sa.Column("last_read_at", sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column("reviewed", sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column("state", sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("patient", schema=None) as batch_op:
        batch_op.drop_column("state")
        batch_op.drop_column("reviewed")
        batch_op.drop_column("last_read_at")

    # ### end Alembic commands ###
