"""empty message

Revision ID: 7afcd405152b
Revises: 374c1d567ec1
Create Date: 2024-07-29 22:23:59.857197

"""

# revision identifiers, used by Alembic.
revision = "7afcd405152b"
down_revision = "374c1d567ec1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table(
    #     "alexa_id_note",
    #     sa.Column("id", sa.Integer(), nullable=False),
    #     sa.Column("alexa_user_id", sa.Text(), nullable=True),
    #     sa.Column("created_at", sa.DateTime(), nullable=True),
    #     sa.Column("updated_at", sa.DateTime(), nullable=True),
    #     sa.PrimaryKeyConstraint("id"),
    # )
    # ### end Alembic commands ###
    pass


def downgrade():
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table("alexa_id_note")
    # ### end Alembic commands ###
