"""empty message

Revision ID: 87baed316f20
Revises: aadd688d9f0d
Create Date: 2024-09-26 22:10:00.523027

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "87baed316f20"
down_revision = "aadd688d9f0d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("report_note", schema=None) as batch_op:
        batch_op.alter_column("user_id", existing_type=sa.INTEGER(), nullable=True)
        batch_op.alter_column("report_id", existing_type=sa.INTEGER(), nullable=True)
        batch_op.alter_column("content", existing_type=sa.TEXT(), nullable=True)
        batch_op.alter_column("created_at", existing_type=sa.DATETIME(), nullable=True)
        batch_op.alter_column("updated_at", existing_type=sa.DATETIME(), nullable=True)

    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.alter_column(
            "username", existing_type=sa.VARCHAR(length=50), nullable=True
        )
        batch_op.alter_column(
            "password", existing_type=sa.VARCHAR(length=255), nullable=True
        )
        batch_op.alter_column(
            "email", existing_type=sa.VARCHAR(length=100), nullable=True
        )
        batch_op.alter_column(
            "name", existing_type=sa.VARCHAR(length=100), nullable=True
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.alter_column(
            "name", existing_type=sa.VARCHAR(length=100), nullable=False
        )
        batch_op.alter_column(
            "email", existing_type=sa.VARCHAR(length=100), nullable=False
        )
        batch_op.alter_column(
            "password", existing_type=sa.VARCHAR(length=255), nullable=False
        )
        batch_op.alter_column(
            "username", existing_type=sa.VARCHAR(length=50), nullable=False
        )

    with op.batch_alter_table("report_note", schema=None) as batch_op:
        batch_op.alter_column("updated_at", existing_type=sa.DATETIME(), nullable=False)
        batch_op.alter_column("created_at", existing_type=sa.DATETIME(), nullable=False)
        batch_op.alter_column("content", existing_type=sa.TEXT(), nullable=False)
        batch_op.alter_column("report_id", existing_type=sa.INTEGER(), nullable=False)
        batch_op.alter_column("user_id", existing_type=sa.INTEGER(), nullable=False)

    # ### end Alembic commands ###
