"""empty message

Revision ID: 9d9b2e058c52
Revises: 0cd3d2d64aa9
Create Date: 2024-04-15 20:34:42.307128

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9d9b2e058c52"
down_revision = "0cd3d2d64aa9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("report", schema=None) as batch_op:
        batch_op.add_column(sa.Column("read", sa.Boolean(), nullable=True))
        batch_op.drop_column("swelling_read")
        batch_op.drop_column("eating_read")
        batch_op.drop_column("diarrhea_read")
        batch_op.drop_column("drainage_read")
        batch_op.drop_column("conscious_read")
        batch_op.drop_column("breathing_read")
        batch_op.drop_column("mood_read")
        batch_op.drop_column("activity_read")
        batch_op.drop_column("stools_read")
        batch_op.drop_column("fever_read")
        batch_op.drop_column("pain_read")
        batch_op.drop_column("constipation_read")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("report", schema=None) as batch_op:
        batch_op.add_column(sa.Column("constipation_read", sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column("pain_read", sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column("fever_read", sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column("stools_read", sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column("activity_read", sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column("mood_read", sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column("breathing_read", sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column("conscious_read", sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column("drainage_read", sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column("diarrhea_read", sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column("eating_read", sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column("swelling_read", sa.BOOLEAN(), nullable=True))
        batch_op.drop_column("read")

    # ### end Alembic commands ###
