"""empty message

Revision ID: aadd688d9f0d
Revises: f7f94a943795
Create Date: 2024-09-19 22:16:21.668394

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "aadd688d9f0d"
down_revision = "f7f94a943795"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "reportnote",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("report_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["report_id"],
            ["report.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("report_note")
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.alter_column(
            "username", existing_type=sa.VARCHAR(length=50), nullable=False
        )
        batch_op.alter_column(
            "password", existing_type=sa.VARCHAR(length=255), nullable=False
        )
        batch_op.alter_column(
            "email", existing_type=sa.VARCHAR(length=100), nullable=False
        )
        batch_op.alter_column(
            "name", existing_type=sa.VARCHAR(length=100), nullable=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.alter_column(
            "name", existing_type=sa.VARCHAR(length=100), nullable=True
        )
        batch_op.alter_column(
            "email", existing_type=sa.VARCHAR(length=100), nullable=True
        )
        batch_op.alter_column(
            "password", existing_type=sa.VARCHAR(length=255), nullable=True
        )
        batch_op.alter_column(
            "username", existing_type=sa.VARCHAR(length=50), nullable=True
        )

    op.create_table(
        "report_note",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("report_id", sa.INTEGER(), nullable=True),
        sa.Column("user_id", sa.INTEGER(), nullable=True),
        sa.Column("content", sa.TEXT(), nullable=True),
        sa.Column("created_at", sa.DATETIME(), nullable=True),
        sa.Column("updated_at", sa.DATETIME(), nullable=True),
        sa.ForeignKeyConstraint(
            ["report_id"],
            ["report.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("reportnote")
    # ### end Alembic commands ###
