"""empty message

Revision ID: aadd688d9f0d
Revises: f7f94a943795
Create Date: 2024-09-19 22:16:21.668394

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "aadd688d9f0d"
down_revision = "f7f94a943795"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.alter_column(
            "username", existing_type=sa.VARCHAR(length=50), nullable=False
        )
        batch_op.alter_column(
            "password", existing_type=sa.VARCHAR(length=255), nullable=False
        )
        batch_op.alter_column(
            "email", existing_type=sa.VARCHAR(length=100), nullable=False
        )
        batch_op.alter_column(
            "name", existing_type=sa.VARCHAR(length=100), nullable=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.alter_column(
            "name", existing_type=sa.VARCHAR(length=100), nullable=True
        )
        batch_op.alter_column(
            "email", existing_type=sa.VARCHAR(length=100), nullable=True
        )
        batch_op.alter_column(
            "password", existing_type=sa.VARCHAR(length=255), nullable=True
        )
        batch_op.alter_column(
            "username", existing_type=sa.VARCHAR(length=50), nullable=True
        )
