"""empty message

Revision ID: c3f184a38ee3
Revises: 1a07dd65c6a8
Create Date: 2024-10-14 15:40:55.764761

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c3f184a38ee3"
down_revision = "1a07dd65c6a8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "alexa_id_note",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("alexa_user_id", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("token", schema=None) as batch_op:
        batch_op.alter_column(
            "token", existing_type=sa.VARCHAR(length=255), nullable=False
        )
        batch_op.alter_column("rememberme", existing_type=sa.BOOLEAN(), nullable=False)
        batch_op.alter_column("created_at", existing_type=sa.DATETIME(), nullable=False)
        batch_op.alter_column("updated_at", existing_type=sa.DATETIME(), nullable=False)

    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.alter_column(
            "username", existing_type=sa.VARCHAR(length=50), nullable=False
        )
        batch_op.alter_column(
            "password", existing_type=sa.VARCHAR(length=255), nullable=False
        )
        batch_op.alter_column(
            "email", existing_type=sa.VARCHAR(length=100), nullable=False
        )
        batch_op.alter_column(
            "name", existing_type=sa.VARCHAR(length=100), nullable=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.alter_column(
            "name", existing_type=sa.VARCHAR(length=100), nullable=True
        )
        batch_op.alter_column(
            "email", existing_type=sa.VARCHAR(length=100), nullable=True
        )
        batch_op.alter_column(
            "password", existing_type=sa.VARCHAR(length=255), nullable=True
        )
        batch_op.alter_column(
            "username", existing_type=sa.VARCHAR(length=50), nullable=True
        )

    with op.batch_alter_table("token", schema=None) as batch_op:
        batch_op.alter_column("updated_at", existing_type=sa.DATETIME(), nullable=True)
        batch_op.alter_column("created_at", existing_type=sa.DATETIME(), nullable=True)
        batch_op.alter_column("rememberme", existing_type=sa.BOOLEAN(), nullable=True)
        batch_op.alter_column(
            "token", existing_type=sa.VARCHAR(length=255), nullable=True
        )

    op.drop_table("alexa_id_note")
    # ### end Alembic commands ###
