"""empty message

Revision ID: c5ee09281e78
Revises: 2130be66323f
Create Date: 2024-10-02 01:10:45.536295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5ee09281e78'
down_revision = '2130be66323f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cognition_state', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('cognition_logs', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('cognition_scale', sa.Integer(), nullable=True))
        batch_op.drop_column('constipation_logs')
        batch_op.drop_column('constipation_state')
        batch_op.drop_column('diarrhea_state')
        batch_op.drop_column('fever_logs')
        batch_op.drop_column('conscious_scale')
        batch_op.drop_column('conscious_state')
        batch_op.drop_column('conscious_logs')
        batch_op.drop_column('fever_state')
        batch_op.drop_column('constipation_scale')
        batch_op.drop_column('diarrhea_logs')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('diarrhea_logs', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('constipation_scale', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('fever_state', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('conscious_logs', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('conscious_state', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('conscious_scale', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('fever_logs', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('diarrhea_state', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('constipation_state', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('constipation_logs', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('cognition_scale')
        batch_op.drop_column('cognition_logs')
        batch_op.drop_column('cognition_state')

    # ### end Alembic commands ###
