"""empty message

Revision ID: d5edfdf9001a
Revises: 3b5267430f69
Create Date: 2026-02-12 23:24:23.014090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5edfdf9001a'
down_revision = '3b5267430f69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('summary', schema=None) as batch_op:
        batch_op.add_column(sa.Column('short_of_breath_state', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('short_of_breath_logs', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('chest_discomfort_state', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('chest_discomfort_logs', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('fatigue_state', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('fatigue_logs', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('palpitation_state', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('palpitation_logs', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('swelling_state', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('swelling_logs', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('syncope_state', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('syncope_logs', sa.String(), nullable=True))
        batch_op.drop_column('chest_discomfort')
        batch_op.drop_column('short_of_breath')
        batch_op.drop_column('swelling')
        batch_op.drop_column('palpitation')
        batch_op.drop_column('syncope')
        batch_op.drop_column('fatigue')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('summary', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fatigue', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('syncope', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('palpitation', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('swelling', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('short_of_breath', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('chest_discomfort', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('syncope_logs')
        batch_op.drop_column('syncope_state')
        batch_op.drop_column('swelling_logs')
        batch_op.drop_column('swelling_state')
        batch_op.drop_column('palpitation_logs')
        batch_op.drop_column('palpitation_state')
        batch_op.drop_column('fatigue_logs')
        batch_op.drop_column('fatigue_state')
        batch_op.drop_column('chest_discomfort_logs')
        batch_op.drop_column('chest_discomfort_state')
        batch_op.drop_column('short_of_breath_logs')
        batch_op.drop_column('short_of_breath_state')

    # ### end Alembic commands ###
