"""empty message

Revision ID: e5554207a734
Revises: c5ee09281e78
Create Date: 2024-10-06 00:06:27.124293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5554207a734'
down_revision = 'c5ee09281e78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pain_state', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('pain_logs', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('pain_scale', sa.Integer(), nullable=True))
        batch_op.drop_column('cognition_scale')
        batch_op.drop_column('eating_scale')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('eating_scale', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('cognition_scale', sa.INTEGER(), nullable=True))
        batch_op.drop_column('pain_scale')
        batch_op.drop_column('pain_logs')
        batch_op.drop_column('pain_state')

    # ### end Alembic commands ###
