"""empty message

Revision ID: ea302dd456b9
Revises: 602be74c86d7
Create Date: 2024-08-14 23:26:00.175517

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ea302dd456b9"
down_revision = "602be74c86d7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("patient", schema=None) as batch_op:
        batch_op.add_column(sa.Column("user_id", sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("patient", schema=None) as batch_op:
        batch_op.drop_column("user_id")

    # ### end Alembic commands ###
