"""empty message

Revision ID: f1d2c16ad13e
Revises: 703386799acf
Create Date: 2026-03-28 15:21:17.668061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1d2c16ad13e'
down_revision = '703386799acf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=255), nullable=True))
        batch_op.create_unique_constraint(None, ['email'])

    with op.batch_alter_table('summary', schema=None) as batch_op:
        batch_op.add_column(sa.Column('spo2_state', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('spo2_logs', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('hrv_state', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('hrv_logs', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('summary', schema=None) as batch_op:
        batch_op.drop_column('hrv_logs')
        batch_op.drop_column('hrv_state')
        batch_op.drop_column('spo2_logs')
        batch_op.drop_column('spo2_state')

    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
