"""empty message

Revision ID: f7f94a943795
Revises: 40d66b3408da
Create Date: 2024-09-17 16:16:09.819037

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f7f94a943795"
down_revision = "40d66b3408da"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("patient", schema=None) as batch_op:
        batch_op.drop_column("user_id")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("patient", schema=None) as batch_op:
        batch_op.add_column(sa.Column("user_id", sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
