"""empty message

Revision ID: 0cd3d2d64aa9
Revises: 5193b57cd38b
Create Date: 2024-04-14 01:31:31.941572

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = "0cd3d2d64aa9"
down_revision = "5193b57cd38b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("report", schema=None) as batch_op:
        batch_op.add_column(sa.Column("pain_state", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("pain_read", sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column("pain_logs", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("breathing_state", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("breathing_read", sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column("breathing_logs", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("fever_state", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("fever_read", sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column("fever_logs", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("stools_state", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("stools_read", sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column("stools_logs", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("drainage_state", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("drainage_read", sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column("drainage_logs", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("activity_state", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("activity_read", sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column("activity_logs", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("conscious_state", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("conscious_read", sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column("conscious_logs", sa.String(), nullable=True))
        batch_op.add_column(
            sa.Column("constipation_state", sa.Integer(), nullable=True)
        )
        batch_op.add_column(sa.Column("constipation_read", sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column("constipation_logs", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("diarrhea_state", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("diarrhea_read", sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column("diarrhea_logs", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("eating_state", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("eating_read", sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column("eating_logs", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("swelling_state", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("swelling_read", sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column("swelling_logs", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("mood_state", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("mood_read", sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column("mood_logs", sa.String(), nullable=True))
        batch_op.drop_column("eating")
        batch_op.drop_column("conscious")
        batch_op.drop_column("pain")
        batch_op.drop_column("breathing")
        batch_op.drop_column("stools")
        batch_op.drop_column("constipation")
        batch_op.drop_column("mood")
        batch_op.drop_column("activity")
        batch_op.drop_column("drainage")
        batch_op.drop_column("diarrhea")
        batch_op.drop_column("swelling")
        batch_op.drop_column("fever")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("report", schema=None) as batch_op:
        batch_op.add_column(sa.Column("fever", sqlite.JSON(), nullable=True))
        batch_op.add_column(sa.Column("swelling", sqlite.JSON(), nullable=True))
        batch_op.add_column(sa.Column("diarrhea", sqlite.JSON(), nullable=True))
        batch_op.add_column(sa.Column("drainage", sqlite.JSON(), nullable=True))
        batch_op.add_column(sa.Column("activity", sqlite.JSON(), nullable=True))
        batch_op.add_column(sa.Column("mood", sqlite.JSON(), nullable=True))
        batch_op.add_column(sa.Column("constipation", sqlite.JSON(), nullable=True))
        batch_op.add_column(sa.Column("stools", sqlite.JSON(), nullable=True))
        batch_op.add_column(sa.Column("breathing", sqlite.JSON(), nullable=True))
        batch_op.add_column(sa.Column("pain", sqlite.JSON(), nullable=True))
        batch_op.add_column(sa.Column("conscious", sqlite.JSON(), nullable=True))
        batch_op.add_column(sa.Column("eating", sqlite.JSON(), nullable=True))
        batch_op.drop_column("mood_logs")
        batch_op.drop_column("mood_read")
        batch_op.drop_column("mood_state")
        batch_op.drop_column("swelling_logs")
        batch_op.drop_column("swelling_read")
        batch_op.drop_column("swelling_state")
        batch_op.drop_column("eating_logs")
        batch_op.drop_column("eating_read")
        batch_op.drop_column("eating_state")
        batch_op.drop_column("diarrhea_logs")
        batch_op.drop_column("diarrhea_read")
        batch_op.drop_column("diarrhea_state")
        batch_op.drop_column("constipation_logs")
        batch_op.drop_column("constipation_read")
        batch_op.drop_column("constipation_state")
        batch_op.drop_column("conscious_logs")
        batch_op.drop_column("conscious_read")
        batch_op.drop_column("conscious_state")
        batch_op.drop_column("activity_logs")
        batch_op.drop_column("activity_read")
        batch_op.drop_column("activity_state")
        batch_op.drop_column("drainage_logs")
        batch_op.drop_column("drainage_read")
        batch_op.drop_column("drainage_state")
        batch_op.drop_column("stools_logs")
        batch_op.drop_column("stools_read")
        batch_op.drop_column("stools_state")
        batch_op.drop_column("fever_logs")
        batch_op.drop_column("fever_read")
        batch_op.drop_column("fever_state")
        batch_op.drop_column("breathing_logs")
        batch_op.drop_column("breathing_read")
        batch_op.drop_column("breathing_state")
        batch_op.drop_column("pain_logs")
        batch_op.drop_column("pain_read")
        batch_op.drop_column("pain_state")

    # ### end Alembic commands ###
