"""initial

Revision ID: 31d6f582095d
Revises: 
Create Date: 2026-03-03 19:04:38.946509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31d6f582095d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alexa_id_note',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alexa_user_id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alexa_user_id')
    )
    op.create_table('patient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('EHR_id', sa.String(length=50), nullable=True),
    sa.Column('alexa_user_id', sa.String(length=50), nullable=True),
    sa.Column('participant_id', sa.String(length=20), nullable=True),
    sa.Column('garmin_id', sa.String(length=50), nullable=True),
    sa.Column('cancer_type', sa.String(length=100), nullable=True),
    sa.Column('cancer_stage', sa.String(length=100), nullable=True),
    sa.Column('treatment_type', sa.String(length=100), nullable=True),
    sa.Column('last_read_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alexa_user_id'),
    sa.UniqueConstraint('garmin_id'),
    sa.UniqueConstraint('participant_id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('admission_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('admission_date', sa.DateTime(), nullable=False),
    sa.Column('discharge_date', sa.DateTime(), nullable=True),
    sa.Column('diagnosis', sa.Text(), nullable=True),
    sa.Column('symptoms', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conversation_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('chain_of_thoughts', sa.Text(), nullable=True),
    sa.Column('symptoms_chest', sa.Text(), nullable=True),
    sa.Column('symptoms_other', sa.Text(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('medication',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('drug_name', sa.String(length=255), nullable=False),
    sa.Column('dosage', sa.String(length=255), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('recorded_by_user_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.ForeignKeyConstraint(['recorded_by_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('note',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('creator_type', sa.String(length=10), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('risk',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('important_of_chest', sa.Float(), nullable=True),
    sa.Column('important_of_heart', sa.Float(), nullable=True),
    sa.Column('important_of_respiration', sa.Float(), nullable=True),
    sa.Column('important_of_hrv', sa.Float(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('summary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('syncope_state', sa.Integer(), nullable=True),
    sa.Column('syncope_logs', sa.String(), nullable=True),
    sa.Column('syncope_read', sa.Integer(), nullable=True),
    sa.Column('palpitation_state', sa.Integer(), nullable=True),
    sa.Column('palpitation_logs', sa.String(), nullable=True),
    sa.Column('palpitation_read', sa.Integer(), nullable=True),
    sa.Column('short_of_breath_state', sa.Integer(), nullable=True),
    sa.Column('short_of_breath_logs', sa.String(), nullable=True),
    sa.Column('short_of_breath_read', sa.Integer(), nullable=True),
    sa.Column('chest_discomfort_state', sa.Integer(), nullable=True),
    sa.Column('chest_discomfort_logs', sa.String(), nullable=True),
    sa.Column('chest_discomfort_read', sa.Integer(), nullable=True),
    sa.Column('swelling_state', sa.Integer(), nullable=True),
    sa.Column('swelling_logs', sa.String(), nullable=True),
    sa.Column('swelling_read', sa.Integer(), nullable=True),
    sa.Column('heart_rate_state', sa.Integer(), nullable=True),
    sa.Column('heart_rate_logs', sa.String(), nullable=True),
    sa.Column('heart_rate_read', sa.Integer(), nullable=True),
    sa.Column('respiration_state', sa.Integer(), nullable=True),
    sa.Column('respiration_logs', sa.String(), nullable=True),
    sa.Column('respiration_read', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('userid', sa.Integer(), nullable=False),
    sa.Column('rememberme', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['userid'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('user_patient_table',
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_patient_table')
    op.drop_table('token')
    op.drop_table('summary')
    op.drop_table('risk')
    op.drop_table('note')
    op.drop_table('medication')
    op.drop_table('conversation_log')
    op.drop_table('admission_history')
    op.drop_table('user')
    op.drop_table('patient')
    op.drop_table('alexa_id_note')
    # ### end Alembic commands ###
