"""sync schema with current models

Revision ID: 3302c235ed43
Revises: 2ec53f3f4d7a
Create Date: 2026-03-11 13:49:10.033786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3302c235ed43'
down_revision = '2ec53f3f4d7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('io_metric', schema=None) as batch_op:
        batch_op.alter_column('io_event_count',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('io_total_volume_ml',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('io_total_volume_measurement_count',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)

    with op.batch_alter_table('medication_execution_metric', schema=None) as batch_op:
        batch_op.alter_column('ad_event_count',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('me_event_count',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('so_event_count',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('med_admin_execution_event_count',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)

    with op.batch_alter_table('preadmission_medication', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('preadmission_medication', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('medication_execution_metric', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('med_admin_execution_event_count',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('so_event_count',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('me_event_count',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('ad_event_count',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('io_metric', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('io_total_volume_measurement_count',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('io_total_volume_ml',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('io_event_count',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
