"""summary level read flag

Revision ID: 3f006f336d43
Revises: 7d3b1f206d81
Create Date: 2026-03-05 13:52:29.321205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f006f336d43'
down_revision = '7d3b1f206d81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('summary', schema=None) as batch_op:
        batch_op.add_column(sa.Column('read', sa.Integer(), nullable=False, server_default='0'))
        batch_op.drop_column('chest_discomfort_read')
        batch_op.drop_column('short_of_breath_read')
        batch_op.drop_column('palpitation_read')
        batch_op.drop_column('respiration_read')
        batch_op.drop_column('heart_rate_read')
        batch_op.drop_column('swelling_read')
        batch_op.drop_column('syncope_read')
        batch_op.alter_column('read', server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('summary', schema=None) as batch_op:
        batch_op.add_column(sa.Column('syncope_read', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('swelling_read', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('heart_rate_read', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('respiration_read', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('palpitation_read', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('short_of_breath_read', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('chest_discomfort_read', sa.INTEGER(), nullable=True))
        batch_op.drop_column('read')

    # ### end Alembic commands ###
