"""add treatment_plan treatment_cycle next_appointment_date to patient

Revision ID: 7d3b1f206d81
Revises: 31d6f582095d
Create Date: 2026-03-03 19:17:15.322352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d3b1f206d81'
down_revision = '31d6f582095d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('treatment_plan', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('treatment_cycle', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('next_appointment_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.drop_column('next_appointment_date')
        batch_op.drop_column('treatment_cycle')
        batch_op.drop_column('treatment_plan')

    # ### end Alembic commands ###
